Feat/6 información de trail + lista de jugadores
GameTrail/gametrail-front pull request #22
Opened 2023-03-11 21:23 UTC by ddiazlop

### Se puede probar con la dirección: http://localhost:3000/trail/1.
# Feats completados
- Información de Trail
- Lista de Jugadores de un Trail
- Responsive
# Posibles Mejoras acorde al Front-end
- Añadir los otros dos componentes correspondientes al chat y lista de juegos de un trail.
- Creación de Trails
> - Lo suyo quizá es crear el trail desde un juego directamente y que de ahí salga un formulario

# Posibles Mejoras una vez esté en Backend
- Permitir que un usuario logeado pueda unirse al trail.
- Añadir botón para permitir expulsar jugadores de un Trail si eres el dueño del mismo.

2023-03-12 23:03 UTC, joscacgom requested changes
![image](https://user-images.githubusercontent.com/91144952/224578918-e4df330c-ca00-496f-84eb-8adad9b9a2c1.png)

El ancho de los botones tiene que ser mas pequeño:
![image](https://user-images.githubusercontent.com/91144952/224578956-707ce397-3ea4-4248-81ee-a1f3da74d9ae.png)

Siguiendo los estilos que hemos seguido en las otras vistas, tampoco al hacer click el background tiene que quedar en ese color rosado.

![image](https://user-images.githubusercontent.com/91144952/224579152-624fa30e-6523-4ebf-a5bf-5827c6f14645.png)

El color del fondo debe de ser más blanco, como en las otras vistas:
![image](https://user-images.githubusercontent.com/91144952/224579096-90b3db60-9efb-4be8-acab-741e1a85c964.png)

El texto, el título, las fecha y el boton de unirse tendria que quedar mas centrado como en la vista de detalles de juego.

2023-03-13 12:56 UTC, ddiazlop commented
Los estilos se realizaron de acorde a los mockups acordados. Por eso simplemente reduciré los botones que no se parecen mucho al los de los mockups y cambiaré el fondo a blanco de acorde al resto de fondos de la página.

2023-03-13 15:36 UTC, ddiazlop commented
Cambiadas las vistas:
![image](https://user-images.githubusercontent.com/80246584/224750909-fefda31c-54e3-4c25-bebb-9504b61bfbe3.png)

2023-03-13 19:16 UTC, joscacgom approved these changes

2023-03-13 19:17 UTC, merged

2023-03-13 19:17 UTC, joscacgom commented
De locos @ddiazlop